### ISSUE TITLE
Tool Paper Tracking Issue

### ISSUE THREAD

**Issue by daemontus** [sybila/biodivine-bn-classifier#1]
This issue summarises the remaining work that's necessary to have a working tool for the tool paper. Keep the discussion related to individual issues in their respective threads (if the issue does not exist, create it). I will update the checkboxes as the issues are resolved. 

- [x] Add (unsafe) support for extra symbolic variables to `lib-param-bn`. This is currently proposed [here](https://github.com/sybila/biodivine-lib-param-bn/pull/39).
- [ ] Finalise `hctl-model-checker` crate using the updated `lib-param-bn` and publish it to `crates.io`.
- [x] Resolve ownership issues of different packages on `crates.io` to avoid losing access to vital crates.
- [x] Migrate existing tree explorer code from `aeon-client` to the new `tauri` app prepared in this repository.
- [ ] Add import/export to some form of "raw result file" such that the model checker can output this file and then we can load it into the tree explorer.
- [ ] Add support for static and dynamic property/assertion annotations in the `.aeon` format (assertion=must be true, property=can be explored in the tree).
- [ ] Actually design and implement the language for static annotations (should be similar to our HCTL syntax).
- [ ] Allow exporting tree nodes as "sketches" with static/dynamic assertions corresponding to properties.

**Comment by daemontus** [comment]
First phase of the project seems to be finished.

 - The app is now working with the existing implementation of decision diagrams.
 - `hctl-model-checker` is largely done and we should soon be able to integrate it into the app.

Upcoming tasks:
 - Integrate `hctl-model-checker` as source of the decision trees.
 - Start adding new features.

**Comment by daemontus** [comment]
Ok, for now, this is effectively closed by #2.
